#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

img = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAA4BJ"
    "REFUWIXFll1oHFUUx393dyabrbvsbrZJuqlCxNWskppWMo3Yl9hiIlqFWjCFvhrBF0GK+lIf"
    "fLR5EPzCJ1Fr1AcFsR8iRGuMIIZSqaZGXC3YxK8YTGN0d7vJneNDOmv2c2aziR4YuGfuOed/"
    "5pz/PXPhfxa1VhkYGEhlMplpEdkUsGAwyNjYWAL4tWICk5OTYlkWIoKThLMWEZRSRXrpfi0d"
    "IBwO09/fz8TERBDIARhrE6gFDmDb9rrBRYSFhQWi0ShAEpgC8JWWqd7gXsGdx7btIryyBNYL"
    "Fpr+kivN4ZrgIoLWugirqAXrBn9oEC7PszUQZPH18argQFkFqibgFdwOhpBvzoHPQC3nyoha"
    "al9agYY5EP7u/KrjygriN6p+udP/DefA5a6eQqRP7nsYrXVNQnqqQF1tyGX+9d13oKb92veO"
    "NMwBXz6PyudAw65dPYVZUc3e0ymopxJgI4Eg2OLJf0M5ABC98BUIoOD8H4uu9hvGAWc9f/hO"
    "Zn/Kgs9H1+3Xu9q7VqAe8JVIjHjsGr544zRTsxkSMQpzoFos1wpUSqRasMUOxcT3f7O3r4/O"
    "104izc2cnZmp+SGeK+BWhVwowg3btjDz5im01mQtCwyDbXfdVtN/Q1ogIoS7DH64lOHuO/oK"
    "+0q309MRZE6VT0RH95SAG3h8/CThcBMX3/4QrTXaNLmyJQxPHAUgsbuVxKMP0vHKMf6MtBb5"
    "lyZQdCMSEVlaWqo9zZQi3r8dlV09/+rgEHz+KT9OfYtPQ8IPRrwJcssQMGHHbj4+8hzJtjha"
    "awYHB0mn0zu4eiHx9Dte9jfRNvoscuEcanvn6o8nFuX5o8exWiNcN/wUzaaJbdvMidCxtxNE"
    "4JadyNRZsr/9jLS2VORAzVGcD0VpO3Ar7LsfGX0JdW0nnDnBZy9/xE2pFEMl7HbWs2MX+f3E"
    "W+x89RnefXoUq7u7ENvzKI48fhgVifHCA48xsGcPN7a0w8gRTh17DyuVcj0tW/cfYubeISyX"
    "UVyWAMCKMmDyDGIGGB5+EmN/F8r0c3rkfazeXs9HtZLuaRT7dJ5LL36Ayv5F4GAvxx8ZYfqd"
    "r+ltEBzq4EDo5m7mx38B4J6rTo2Ce2pBI8G9gG/atdyLDuUtKBpEyWRS0ul0EVEcx2ritr9W"
    "TNPE7/dj23Y7MFfJpkUplQWWN+NRSi0Chzxn/F/IPzlRiedgNxiOAAAAAElFTkSuQmCC")

