#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

img = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABA5J"
    "REFUWIXtll1MU2cYx3/nox+0BVqB0lEhQNkUhzqyiWZxUTxL5sjmEm5MNsKyZC5L5uUSNubY"
    "XBSmxkSNmduFM3Zhbl4w3RY/yOpGsmRLNBHdIARFHCKfhfJdPtpzdtEVqIyWBNAb/zfnfZ8n"
    "7/P/5X3Oe94j8KBKz3+HzhJg1GvEnDw+J7+UOqmUSBGBwg92kJybC4DeFFhWcwCbs0mOCIi6"
    "Ilp/S0RvCYE5n+tfVoArVY3ynGDW1kHG+g0A08+lVMf1/QDUVdYDzAUAMK2YWHLjsP4zDktc"
    "NqMF6jHAY4D/PwWz9Jqs3DtXwU4ENNpJF77ynA1WKPmintARFYBenhCOeH4Ir/F+qDydFEci"
    "Atp7n1H7xZQnfr76MXfgXAU7Py0nbawRJ07aubnHRxARDcF9lBXVR3GRQqe2T9kUcv/TlxRH"
    "YnkZGZUVZBc/yTvR6kcHaKv2AbQO0GRaTTfAq+Y/isLp0ioa36jk3epjuFARX/cqT13c+NGb"
    "AC19NG0vgBcbPWeiWURvgRjic3e+XL/5yMXcqSAbfnKc+gbeKgAQ3vbcBV7QTii/0ItL9ZOG"
    "gADw/bcYhPc91VHrs9CXMNg3uWsH+T/+wwnMGdMX2HGbskbbr2yiF9fYbZJ9OurQ0ADch3As"
    "pHT0HdAmpg7uJQHiZeG05yw2EgEOfY5dAA0LfcerUGWJ7PQUhMsOj1biV9SDe0kouyCf4SVM"
    "iwNImvRtKOUy/VevAc+HwwWlXAK4L9FRGGDLylO11QxKAsDKIn52BhG22QMtVzpZGwtAiJgp"
    "H39J5lZLrEWL0kmlZPY0+g5MdPrx1XYTX2DDnJs4He86fXd6PNo4huvAmjk502oLCRuTY/FE"
    "B/A3DxXb3XJN17B3NkCx3S0D1N9n4JksrKhKu9WI/utJjz2cq7mV07F4ANEotfTiQzQbGfy9"
    "h8TNdoCWXkYA7qR78u6oE+r63qJmAAy/ai0Todx66239jVjuMQGEOKmhhxEcCRa57ZM2oC2Q"
    "V/tsQ0/IhFRANIg3hvMCsv/v8Thx32iDGjqGBhmR1NgAkT+l2VtewZqpn9kBvaiONg8T6JtS"
    "pSRZ1Tl0DF/zqZJVUnUOHUNXfXjPd4MoqDqHLpDrXqcGRsZVjMKUmKFjqM6LbVtKhMd1d83s"
    "afQPkc5mwJRlxJCqx5RlxJRlJHPPqumx3irPjJNkNEkgbbcLU5YRs9OAIVXPvcO3olnEvA1J"
    "2+1i+KYP0SBiXhV6EVN3Zc5UkEU0SZizZuSvAeQ4EWNOwuIAAOLX2SLmkmGmddo8ayxrrQsp"
    "/ch/SB45QKgFheWH0cgnGAToeLgA2w9cAEANTiKK83V02TTTAlFS8Q/pHj7ApbIi0ASC4xo5"
    "SteyurV6jj0Y+hezjEXWj4VyvAAAAABJRU5ErkJggg==")

