name: test_quick

on:
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    inputs:
      args:
        type: string
        default: ''
        description: 'Additional arguments to Aptest'

jobs:

  test_quick:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        APTEST_MUPDF_LOCATION: [
                '-m "git:-b 1.28.x"',
                '-m "git:"',
                ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: test_quick
        env:
          APTEST_args: ${{inputs.args}}
          ARTIFEX_SOFTWARE_SSH_KEY: ${{secrets.ARTIFEX_SOFTWARE_SSH_KEY}}
          APTEST_MUPDF_LOCATION: ${{matrix.APTEST_MUPDF_LOCATION}}
        shell: python
        run: |
            import subprocess
            import sys
            subprocess.run(f'git clone https://github.com/ArtifexSoftware/aptest.git', shell=1, check=1)
            subprocess.run(f'{sys.executable} aptest/aptest.py -a APTEST_MUPDF_LOCATION -p . --4llm git: --layout git: build test -t p -e PYMUPDF_TEST_QUICK=1 -a APTEST_args', shell=1, check=1)
